---
title: "Social Influece: Agent-based simulation"
author: "Alejandro Ramos Usaj"
date: "2022-08-25"
bibliography: "SocialInfluenceSimulationbib.bib"
biblio-style: "apalike"
output: 
  md_document:
    variant: markdown_github
---

# Simulation Summary

This repository contains the code for an agent-based simulation of the relationship between individual metacognition and social information use (i.e. social influence).

Our simulation takes inspiration from the work by @Rollwage2021. The difference is that instead of modeling individual integration of secuential information, we model the integration of social and individual-specific information.

For our simulation we try to model the experimental task described by @Voss2008 and employed (albeit modified) by @Germar2014 in the context of a social influence experiment. Briefly, this task presents a square matrix colored with two different colors in varying proportions while the subject task is to decide which color is predominant. The matrix size, colors, and proportions vary within the literature. @Voss2008 reports using "Squares of 200 × 150 screen pixels" while @Germar2014 reports "Squares of 128 × 128 orange and blue pixels were presented at a resolution of 512 × 512 screen pixels". As different colors, some authors use orange and blue [@Germar2014], while others use orange, green, or blue. Lastly, from the perspective of one color, @Voss2008 reports using 56%, 53%, 50%, 47%, or 44% proportions, while @Germar2014 employs 48%, 49%, 50%, 51%, 52%.

Since only one paper [@Germar2014] that we are aware of has given detailed numerical summaries of performance with this task (in a control situation), we use those values as a reference for subject performance. In the following table, we present the aforementioned results.

Following @Rollwage2021, we model a subject reciving one sample of information per trial denoted as $X_{ind} \sim \mathcal{N}(\mu,\sigma^2)$, which is the information sampled by individual. Within this experimental task, $\mu$ always equals the proportion for a fixed color (like blue) and therefore remains the same for all subjects under the same condition. Moreover this value usually varies within values like .48 or .52 since values \$\geq\$0.60 and \$\leq\$0.40 are too easy for subjects given previous empirical evidence. On the other hand, $\sigma^2$ remains the same for all conditions but can be common to all subjects or vary in a subject-specific manner (noted, $\sigma_i^2$) following a given random distribution. As a first approach we set $\sigma^2 = 0.025$ (you can check the `pilot` folder for details on this number).

Thus, for one of the proportions given in @Germar2014 we would have something like $X_{ind} \sim \mathcal{N}(0.48, 0.025)$. The common mean ($\mu$) corresponds to the actual world state[@Rollwage2021] (i.e. the correct color proportion) and the sampled value corresponds to perceptual information (in a continuum) that defines the binary decision. We formalize each agent's decision as

$decision(x_{ind}) = \left\{\begin{array}{lr}1 & \text{if } x_{ind} \geq 0.5 \\ 0 & \text{if } x_{ind}\leq 0.5\end{array}\right\}$

where $x_{ind}$ is a realization of the random variable $X_{ind}$, 1 represents some arbitrary color and 0 represents its complement color.

Confidence in the individual decision is estimated by the log-odds in favour of the chosen world state and using the logistic function the log-odds can be transformed into the probability of answering correctly [@Rollwage2021].

After the initial decision, the agent receives additional information in the form of answers given by other agents modeled as previously described. Nonetheless, we can manipulate the other agent's accuracy by sampling sigma from a distribution. Thus, in the simplest case all agents have the same $\sigma^2$, which means that the precision of their information is the same. In another scenario, the precision of each agent depends upon a random process (modeled by an inverse gamma distribution) as $\sigma^2 \sim IG(\alpha,\beta)$ where the mean is fixed at 0.025. Since there are potentially infinite values of $\alpha$ and $\beta$ with the same mean, we vary over different combinations of parameters that satisfy the above condition. 
